version: '3'

services:
  gpt4free:
    shm_size: 2gb
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - gpt4free_data:/app
    ports:
      - '8080'
      - '${PORT_2}:1337'
      - '${PORT_3}:7900'
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}

volumes:
  gpt4free_data:
