version: '3'

services:
  gpt4free:
    shm_size: 2gb
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - gpt4free_data:/app
      - har_and_cookies:/app/har_and_cookies
      - generated_media:/app/generated_media
    ports:
      - '8080'
      - '1337:1337'
      - '7900'
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
    networks:
      - coolify

volumes:
  gpt4free_data:
  har_and_cookies:
  generated_media:

networks:
  coolify:
    external: true  # ✅ ini penting, karena network-nya dibuat oleh Coolify
