[project]
name = "gpt4free"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "bjo163", email = "bjo163@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "requests",
    "pycryptodome",
    "curl_cffi>=0.6.2",
    "aiohttp",
    "certifi",
    "browser_cookie3",
    "nest-asyncio2",
    "werkzeug",
    "pillow",
    "platformdirs",
    "fastapi",
    "uvicorn",
    "flask[async]",
    "brotli",
    "beautifulsoup4",
    "setuptools",
    "python-multipart",
    "a2wsgi",
    "python-dotenv",
    "ddgs",
    "numpy",
    "PyYAML",
    "websocket-client",
    "pystray",
    "cryptography",
]

[project.scripts]
gpt4free = "g4f.cli:main"
rocksoul = "g4f.rocksoul_platform:main"

[tool.uv.build-backend]
module-name = "g4f"
module-root = ""

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
