[project]
name = "gpt4free"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "bjo163", email = "bjo163@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
gpt4free = "gpt4free:main"
rocksoul = "g4f.rocksoul_platform:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
